default:
  outputs:
    dev:
      type: duckdb
      path: target/local.db
      threads: 8
      extensions:
        - httpfs
        - parquet
        - sqlite_scanner
      external_root: ../data/
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
