default:
  outputs:
    dev:
      type: duckdb
      path: data/local.duckdb
      plugins:
        - module: datadex.plugins.frictionless
      threads: 8
      extensions:
        - httpfs
        - parquet
        - sqlite
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
      external_root: data
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
