version: 2

sources:
  - name: github
    tables:
      - name: yellow_taxi_trips
        meta:
          external_location: https://raw.githubusercontent.com/pablobarbera/data-science-workshop/master/modeling-viz/taxi-trips.csv
      - name: energy
        meta:
          external_location: https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv
      - name: co2_global_trend
        description: "Trends in Atmospheric Carbon Dioxide"
        meta:
          external_location: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_trend_gl.csv
  - name: ethereum
    tables:
      - name: blocks
        meta:
          external_location: "parquet_scan('s3://aws-public-blockchain/v1.0/eth/blocks/*.parquet', HIVE_PARTITIONING=1)"
