project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000
  render:
    - README.md
    - notebooks

format:
  html:
    anchor-sections: true
    smooth-scroll: true

website:
  title: "Datadex"
  repo-url: https://github.com/davidgasquez/datadex
  repo-actions: [edit, issue]
  page-footer: Made with ❤️ by David Gasquez
  navbar:
    search: true
    logo: https://em-content.zobj.net/thumbs/120/google/350/package_1f4e6.png
    left:
      - text: "Notebooks"
        menu:
          - text: "Quarto Example"
            file: notebooks/quarto.ipynb
          - text: "Pyscript"
            file: notebooks/pyscript.ipynb
          - text: "Climate"
            file: notebooks/climate.ipynb
          - text: "DuckDB and IPFS"
            file: notebooks/duckdb-ipfs.ipynb
          - text: "BRLDA"
            file: notebooks/brlda.ipynb
      - text: "dbt Docs"
        file: docs
      - text: "Evidence Reports"
        file: reports
