project:
  type: website
  output-dir: .quarto/output
  render:
    - README.md
    - notebooks

format:
  html:
    anchor-sections: true
    smooth-scroll: true

website:
  title: "Datadex"
  repo-url: https://github.com/davidgasquez/datadex
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - text: "Home"
        file: README.md
      - text: "Quarto Example"
        file: notebooks/quarto.ipynb
      - text: "dbt Docs"
        file: docs
