name: "datadex"
version: "1.0.0"
config-version: 2

profile: "default"

target-path: "target"
clean-targets:
  - "logs"
  - "target"
  - "database"
  - "dbt_packages"

models:
  datadex:
    +materialized: table
    +pre-hook:
      - install 'httpfs'
      - load 'httpfs'
      - "{{ dbt_external_tables.stage_external_sources() }}"
    +post-hook:
      - export database 'database' (format parquet);
