[project]
name = "datadex"
version = "0.1.0"
dependencies = [
    "altair",
    "dagster-dbt",
    "dagster",
    "dbt-core",
    "dbt-duckdb==1.6.0",
    "deltalake",
    "duckdb",
    "frictionless",
    "ipykernel",
    "itables",
    "ipywidgets",
    "matplotlib",
    "nbclient",
    "nbformat",
    "numpy",
    "pandas",
    "polars",
    "pyarrow",
    "pygwalker[notebook]",
    "regex",
    "tqdm",
    "vegafusion[embed]",
    "zstandard",
]
requires-python = ">=3.10, <3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["dagit", "shandy-sqlfmt[jinjafmt]"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datadex"]

[tool.dagster]
module_name = "datadex"
