[project]
name = "datadex"
version = "1.0.0"
dependencies = [
    "altair",
    "dagster-dbt",
    "dagster-duckdb-pandas",
    "dagster",
    "dbt-core",
    "dbt-duckdb",
    "duckdb",
    "frictionless",
    "ipykernel",
    "ipywidgets",
    "itables",
    "matplotlib",
    "nbclient",
    "nbformat",
    "pyarrow",
    "regex",
]

requires-python = ">=3.10, <=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["dagit", "shandy-sqlfmt[jinjafmt]", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datadex"]

[tool.dagster]
module_name = "datadex"
