version: 2

models:
  - name: yellow_taxi_trips
    description: ""
    columns:
      - name: vendor_id
        description: "A code indicating the TPEP provider that provided the record."
      - name: pickup_at
        description: "The date and time when the meter was engaged."
      - name: dropoff_at
        description: "The date and time when the meter was disengaged."
      - name: passenger_count
        description: "The number of passengers in the vehicle."
      - name: trip_distance
        description: "The elapsed trip distance in miles reported by the taximeter."
      - name: payment_type
        description: |
          A numeric code signifying how the passenger paid for the trip.
          1= Credit card
          2= Cash
          3= No charge
          4= Dispute
          5= Unknown
          6= Voided trip
      - name: fare_amount
        description: "The time-and-distance fare calculated by the meter."
      - name: tip_amount
        description: "This field is automatically populated for credit card tips. Cash tips are not included."
      - name: tolls_amount
        description: "Total amount of all tolls paid in trip."
      - name: total_amount
        description: "The total amount charged to passengers. Does not include cash tips."
