name: CI

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Run 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        run: make build
      - name: Run dbt
        run: docker run -t -v $PWD/:/workspaces/datadex/ davidgasquez/datadex:latest make run
      - name: Generate Docs
        run: docker run -t -v $PWD/:/workspaces/datadex/ davidgasquez/datadex:latest make docs
      # - run: mkdir -p docs
      # - run: cp dbt/target/*.json target/index.html target/graph.gpickle docs/
      # - name: Publish Docs
      #   uses: JamesIves/github-pages-deploy-action@4.0.0
      #   with:
      #     branch: gh-pages
      #     folder: docs
