name: CI

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Run 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        run: docker build -t dbt .
      - name: Get Dependencies
        run: docker run -t --entrypoint dbt -v $PWD/dbt:/workspaces/datadex/dbt dbt deps
      - name: Run dbt
        run: docker run -t --entrypoint dbt -v $PWD/dbt:/workspaces/datadex/dbt dbt run
      - name: Run dbt tests
        run: docker run -t --entrypoint dbt -v $PWD/dbt:/workspaces/datadex/dbt dbt test
      - name: Generate Docs
        run: docker run -t --entrypoint dbt -v $PWD/dbt:/workspaces/datadex/dbt dbt docs generate
      - run: mkdir -p docs
      - run: cp dbt/target/*.json dbt/target/index.html target/graph.gpickle docs/
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
