name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Publish Documentation 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        run: docker build -t dbt .
      - name: Get Data
        run: docker run -t --entrypoint make -v $PWD:/workspaces/datadex dbt data
      - name: Get Dependencies
        run: docker run -t --entrypoint dbt -v $PWD:/workspaces/datadex dbt deps
      - name: Run dbt
        run: docker run -t --entrypoint dbt -v $PWD:/workspaces/datadex dbt run
      - name: Generate Docs
        run: docker run -t --entrypoint dbt -v $PWD:/workspaces/datadex dbt docs generate
      - run: mkdir -p docs
      - run: cp target/*.json target/index.html target/graph.gpickle docs/
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
      - name: Upload to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: "database"
      - run: echo ${{ steps.web3.outputs.url }}
