version: 2

models:
  - name: yellow_taxi_vendors
    description: "Some stats at the vendor level."
    columns:
      - name: vendor_id
        description: "A code indicating the TPEP provider."
      - name: first_trip
        description: "First trip timestamp."
      - name: last_trip
        description: "Last trip timestamp."
      - name: avg_passenger_count
        description: "Average passenger count per trip."
      - name: avg_trip_distance
        description: "Average trip distance per trip."
