version: 2

models:
  - name: test
    description: Test
    columns:
      - name: id
        description: Test
        tests:
          - unique
          - not_null
      - name: other
        description: Test
        tests:
          - unique
          - not_null
