version: 2

sources:
  - name: main
    tables:
      - name: fifa_countries
        external:
          location: "https://raw.githubusercontent.com/fivethirtyeight/data/master/fifa/fifa_countries_audience.csv"
